# Generated by Django 4.2.1 on 2023-08-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetApp', '0003_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_file',
        ),
    ]
